apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All managed applications
resources:
- bootstrap-application.yaml
- kairos-operator-application.yaml

commonLabels:
  managed-by: argocd
